### ISSUE TITLE
SimuNode.cpp doesn't build yet

### ISSUE THREAD

**Issue by ejalaa12** [ENSTA-Bretagne-Shepherd/Shepherd-Ros-Structure#1]
Le code (ENSTA-Bretagne-Shepherd@187e2f8274bd9bc42d73041c3b6e6bd80e71e2b6) n'est pas encore terminé je pense.
Des que tu peux le terminer. 
Fait un `catkin_make` et si ca compile correctement test le noeud avec:
```bash
rosrun shepherd_simu SimuNode
```

**Comment by simchanu29** [comment]
Done
